import type { NextConfig } from "next";

const withPWA = require("@ducanh2912/next-pwa").default({
    dest: "public",
    // IMPORTANT: Do NOT cache HTML navigation responses. When the PWA reopens,
    // we need the server (middleware + page.tsx) to run its SSR auth check and
    // redirect authenticated users to /home. Serving a cached HTML shell would
    // bypass that check and show the landing page to logged-in users.
    cacheOnFrontEndNav: false,
    aggressiveFrontEndNavCaching: false,
    reloadOnOnline: true,
    swcMinify: true,
    disable: process.env.NODE_ENV === "development",
    workboxOptions: {
        disableDevLogs: true,
        // Explicitly exclude all HTML page routes from runtime caching.
        // Static assets (_next/static, fonts, images) are still precached/cached
        // by the default workbox configuration generated by next-pwa.
        runtimeCaching: [
            {
                // All same-origin HTML navigations → always hit the network.
                // This covers: /, /home, /tasks, /regimens, /achievements,
                // /journal, /chat, /calendar, /settings, /onboarding, /login, /signup
                urlPattern: ({ request }: { request: Request }) =>
                    request.mode === "navigate",
                handler: "NetworkOnly" as const,
            },
        ],
    },
});

const nextConfig: NextConfig = {};

export default withPWA(nextConfig);
